<?php
/*
 * classe User
 * @author Agathe Dupuis
 * @date 04/10/24
 */
class Announcement
{
    // Attribut
    private $id; // ID auto-generated by the database
    private $id_cat_gender; // int
    private $id_user; // key link User class
    private $creation_date; // string
    private $description; // string
    private $cat_name; // int
    private $cat_birth; // date
    private $cat_loof; // bool

    // Methode
    public function __construct(int $id_cat_gender, int $id_user, DateTime $creation_date, string $description, string $cat_name,DateTime $cat_birth, bool $cat_loof = false) {
        $this->id_cat_gender = $id_cat_gender;
        $this->id_user = $id_user;
        $this->creation_date = $creation_date;
        $this->description = $description;
        $this->cat_name = $cat_name;
        $this->cat_birth = $cat_birth;
        $this->cat_loof = $cat_loof;

    }
}

?>